#!/bin/sh

usage()
{
    cat <<__EOF__
Usage: $(basename $0) [ -u username ]

Options:
  -u username           - Send mail to the specified user instead of
                          \${USER}@$domain
__EOF__

    exit ${1-1}
}

log()
{
    echo "$(basename $0): $1" >&2
}

pktcount()
{
    netstat -s -p tcp | grep 'control packets' | awk '{print $1}'
}

domain=$(hostname)
domain=${domain#*.}
[ "$domain" = $(hostname -s) ] && domain=

while [ $# -gt 0 ]; do
    case $1 in
    -h|--help)
        usage 0
        ;;
    -u)
        shift
        if [ -z "$1" ]; then
            log "username must be a non-empty string"
            usage
        fi

        mailto="$1"@$domain
        ;;
    *)
        usage
        ;;
    esac
done

: ${mailto=${USER}@${domain}}

if [ -n "$domain" ]; then
    log "sending notification mail to $mailto"
else
    log "no domain found, not sending mail"
fi

logcount=0
count=$(pktcount)

while true; do
    oldcount=$count
    count=$(pktcount)
    if [ $((count - oldcount)) -gt 1000 ]; then
        sudo tcpdump -i lo0 -w /d2/tmp/lo${logcount}.cap 2>/dev/null &
        tdpid=$!
        sleep 30
        kill -INT $tdpid
        mail -s $(basename $0) $mailto <<__EOF__
A possible packet storm capture has been saved in /d2/tmp/lo${logcount}.cap
on $(hostname -s). There were $((count - oldcount)) TCP control packets seen
in the last minute.
__EOF__
        logcount=$((logcount + 1))
    fi
    sleep 60
done
