#!/bin/sh

usage()
{
    echo "$(basename $0): <file>"
    exit 1
}

if [ $# -ne 1 ]; then
    usage
fi

ctfdump -t $1 | grep -e '<[0-9]\+>' -e '\[[0-9]\+\]' | awk '{print $3}' | \
    sort | uniq -c | sort
