#!/bin/sh

set -e

while [ $# -gt 0 ]; do
    commit=$1
    shift

    url="https://cgit.freebsd.org/src/commit/?id=${commit}"
    echo $url
    if which xclip >/dev/null; then
        echo $url | xclip
    fi
done
