#!/bin/sh

setdb()
{
	[ $# -ne 1 ] && echo "usage: setdb < db-name >" && return 1

	local _DB_DIR _DB

	_DB_DIR=${HOME}/src/cscope

	for _DB in $(ls ${_DB_DIR}); do
		if [ "$_DB" = "$1" ]; then
			export CSCOPE_DB=${_DB_DIR}/${1}
			return 0
		fi
	done

	echo "setdb: unknown src tree"
	return 1
}

regendb()
{
	[ $# -gt 1 ] && echo "usage: regendb [ db-name ]" && return 1

	local _DB_DIR _DB

	_DB_DIR=${HOME}/src/cscope

	if [ $# -eq 0 ]; then
		for _DB in $(ls ${_DB_DIR}); do
			$(cd ${_DB_DIR}/${_DB} && ./csdbgen.sh && \
			  cscope -b -q -k)
			return 0
		done
	else
		for _DB in $(ls ${_DB_DIR}); do
			if [ "$_DB" = "$1" ]; then
				$(cd ${_DB_DIR}/${1} && ./csdbgen.sh && \
				  cscope -b -q -k)
				return 0
			fi
		done
	fi

	echo "setdb: unknown src tree"
	return 1
}

unsetdb()
{
	[ $# -ne 0 ] && echo "usage: unsetdb" && return 1

	unset CSCOPE_DB
}
