#!/bin/sh

usage()
{
    cat <<__EOF__
Usage: $(basename $0) [ -b <branch> ] [ -p <parent-branch> ]

Options:
  -b <branch>           -- Branch head to use. Defaults to the current branch.

  -p <parent-branch>    -- Parent branch to diff against. Defaults to
                           markj-kernel-config.
__EOF__
    exit 1
}

err()
{
    echo "$(basename $0): $1" >&2
    exit 1
}

PBRANCH=markj-kernel-config
BRANCH=$(git branch | awk '/^\*/{print $NF}')
if [ $? -ne 0 ]; then
    err "couldn't obtain git branch list"
fi

while [ $# -gt 0 ]; do
    case $1 in
    -b)
        shift
        BRANCH=$1
        ;;
    -p)
        shift
        PBRANCH=$1
        ;;
    *)
        usage
        ;;
    esac
    shift
done

if [ $# -gt 0 ]; then
    usage
fi

tmpfile=$(mktemp)
chmod a+r $tmpfile
git diff ${PBRANCH}..${BRANCH} > $tmpfile
less $tmpfile

DIR=patches/${BRANCH#[0-9]*-}
ssh markj@freefall.freebsd.org "mkdir -p public_html/${DIR}"

COUNTF=$(mktemp)
scp markj@freefall.freebsd.org:public_html/${DIR}/count $COUNTF 2>/dev/null
if [ $(stat -f "%z" $COUNTF) -eq 0 ]; then
    COUNT=1
else
    COUNT=$(cat $COUNTF)
    COUNT=$(($COUNT + 1))
fi
echo $COUNT > $COUNTF
scp $COUNTF markj@freefall.freebsd.org:public_html/${DIR}/count

FILE=${DIR}/${BRANCH#[0-9]*-}-${COUNT}.diff
scp $tmpfile markj@freefall.freebsd.org:public_html/$FILE
if [ $? -ne 0 ]; then
    exit 1
fi

echo "http://people.freebsd.org/~markj/${FILE}"
