#!/bin/sh

#
# todo:
#   - support for incremental rebuilds of images
#   - ssh keys
#   - i386 images
#

usage()
{
    echo "usage: $(basename $0) [-t] [-a <arch>] [-p <pkgs>] [-s <size>] <img>" >&2
    exit 1
}

# Bootstrap packages.
bootstrap()
{
    local md mdir pfile pkgs

    pfile=$1
    pkgs=$2

    md=$(mdconfig -f $pfile)
    mdir=$(mktemp -d)

    mount /dev/$md $mdir

    # Set up to install packages.
    cp -f /etc/resolv.conf ${mdir}/etc/resolv.conf
    chroot ${mdir} env ASSUME_ALWAYS_YES=yes /usr/sbin/pkg bootstrap -y

    # Do the thing.
    echo "$pkgs" | tr ',' ' ' | xargs chroot $mdir env ASSUME_ALWAYS_YES=yes \
        /usr/local/sbin/pkg install

    # Clean up, clean up.
    umount $mdir
    rmdir $mdir
    mdconfig -d -u ${md#md}
}

cleanup()
{
    if [ $TMPFS ]; then
        umount $DESTDIR
    else
        rm -rf $DESTDIR || :
        chflags -R 0 $DESTDIR || :
        rm -rf $DESTDIR
    fi

    rm -f $PARTFILE
}

# Manually add a file to the image.
logfile()
{
    local file root size

    file=$1
    root=$2

    size=$(stat -f '%z' ${root}/${file})
    echo "./$file type=file uname=root gname=wheel mode=0644 size=$size" >> ${root}/METALOG
}

# Create custom system configuration files.
install_config()
{
    local destdir fstab localtime rcconf srcconf

    destdir=$1

    fstab=etc/fstab
    cat > ${destdir}/$fstab <<__EOF__
/dev/gpt/rootfs / ufs rw 1 1
/dev/gpt/swapfs none swap sw 0 0
none /proc procfs rw 0 0
none /dev/fd fdescfs rw 0 0
${IPADDR}:$(pwd) /usr/src nfs ro 0 0
__EOF__

    localtime=etc/localtime
    cp -f /$localtime ${destdir}/$localtime

    rcconf=etc/rc.conf
    cat > ${destdir}/$rcconf <<__EOF__
ifconfig_vtnet0="DHCP"
ipv6_activate_all_interfaces="YES"
ipv6_cpe_wanif="vtnet0"

sendmail_enable="NONE"
sshd_enable="YES"
__EOF__

    srcconf=etc/src.conf
    cat > ${destdir}/$srcconf <<__EOF__
KERNCONF?= BHYVE
__EOF__

    wallcmosclock=etc/wall_cmos_clock
    touch ${destdir}/$wallcmosclock

    logfile $fstab $destdir
    logfile $localtime $destdir
    logfile $rcconf $destdir
    logfile $srcconf $destdir
    logfile $wallcmosclock $destdir
}

#
# Execution begins here.
#

set -e

ARCH=$(uname -m)
IPADDR=
PARTSIZE=10g
PACKAGES=
TMPFS=
while getopts a:i:p:s:t o; do
    case "$o" in
    a)
        ARCH=$OPTARG
        ;;
    i)
        IPADDR=$OPTARG
        ;;
    p)
        PACKAGES=$OPTARG
        ;;
    s)
        PARTSIZE=$OPTARG
        ;;
    t)
        TMPFS=1
        ;;
    ?)
        usage
        ;;
    esac
    shift $((OPTIND-1))
done

if [ -n "$PACKAGES" -a $(id -u) -ne 0 ]; then
    echo "$(basename $0): must be root to install packages" >&2
    exit 1
elif [ "$TMPFS" -a $(id -u) -ne 0 ]; then
    echo "$(basename $0): must be root to use tmpfs" >&2
    exit 1
fi

if [ -z "$IPADDR" ]; then
    ifconfig bridge0 >/dev/null || exit 1
    IPADDR=$(ifconfig bridge0 | grep -E '^[[:space:]]*inet' | head -n 1 | \
        awk '{print $2}')
fi

IMAGE=${1:-/tmp/vm.raw}
OBJDIR=/usr/obj/$(readlink -f $(pwd))
PARTFILE=$(mktemp)

DESTDIR=$(mktemp -d)
if [ $TMPFS ]; then
    mount -t tmpfs tmpfs $DESTDIR
fi

trap "cleanup; exit 1" EXIT SIGINT SIGHUP SIGTERM

make -j $(sysctl -n hw.ncpu) -s -DNO_ROOT DESTDIR=$DESTDIR KERNCONF=BHYVE MACHINE=$ARCH TARGET_ARCH=$ARCH \
    DISTDIR= installworld installkernel distribution

install_config $DESTDIR

makefs -B little -f $(cat ${DESTDIR}/METALOG | wc -l) -o label=VM -M $PARTSIZE \
    -F ${DESTDIR}/METALOG $PARTFILE $DESTDIR

if [ -n "$PACKAGES" ]; then
    bootstrap $PARTFILE $PACKAGES
fi

mkimg -s gpt -f raw -b ${DESTDIR}/boot/pmbr \
    -p freebsd-boot/bootfs:=${DESTDIR}/boot/gptboot \
    -p freebsd-swap/swapfs::2G \
    -p freebsd-ufs/rootfs:=${PARTFILE} \
    -o $IMAGE

rm -f $PARTFILE
