#!/bin/sh

case $(uname) in
FreeBSD)
    if ifconfig iwn0 >/dev/null 2>&1; then
        interf=iwn0
    elif ifconfig run0 >/dev/null 2>&1; then
        interf=run0
    fi
    ifconfig wlan0 >/dev/null 2>&1 || ifconfig wlan create wlandev $interf
    ;;
Linux)
    ifconfig wlan0 up
    iwconfig wlan0 channel auto
    ;;
esac

sleep 1
wpa_supplicant -i wlan0 -c /etc/wpa_supplicant.conf -B
sleep 1

case $(uname) in
FreeBSD)
    dhclient wlan0
    ;;
Linux)
    dhcpcd wlan0
    ;;
esac
