#!/bin/sh

case $(uname) in
FreeBSD)
    case $(hostname) in
    charmander)
        interf=ath0
        if ifconfig ath0 >/dev/null 2>&1; then
            interf=ath0
        fi
        ;;
    oddish)
        if ifconfig iwn0 >/dev/null 2>&1; then
            interf=iwn0
        fi
        ;;
    esac

    # Test for my USB wlan dongle but let it be overridden.
    if [ -z "$interf" ] && ifconfig run0 >/dev/null 2>&1; then
        interf=run0
    fi

    ifconfig wlan0 >/dev/null 2>&1 || \
        ( ifconfig wlan create wlandev $interf && ifconfig wlan0 up )
    ;;
Linux)
    ifconfig wlan0 up
    iwconfig wlan0 channel auto
    ;;
esac

wpapid=$(pgrep wpa_supplicant)
if [ -n "$wpapid" ]; then
    echo "Killing wpa_supplicant"
    kill $wpapid
else
    sleep 1
fi
wpa_supplicant -i wlan0 -c /etc/wpa_supplicant.conf -B
sleep 1

case $(uname) in
FreeBSD)
    dhclient wlan0
    ;;
Linux)
    dhcpcd wlan0
    ;;
esac
