#!/bin/sh

case $(uname) in
FreeBSD)
    ifconfig wlan create wlandev iwn0
    ;;
Linux)
    ifconfig wlan0 up
    iwconfig wlan0 channel auto
    ;;
esac

wpa_supplicant -i wlan0 -c /etc/wpa_supplicant.conf -B
sleep 1

case $(uname) in
FreeBSD)
    dhclient wlan0
    ;;
Linux)
    dhcpcd wlan0
    ;;
esac
